import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Definisikan font Poppins
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Sertakan semua weight yang akan Anda gunakan
  variable: "--font-poppins", // Membuat font Poppins tersedia sebagai CSS variable
});

export const metadata: Metadata = {
  title: "Project MicroData",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Tambahkan variabel font Poppins ke className body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
      {/* Tag <link> untuk Google Fonts dihapus karena next/font menanganinya */}
    </html>
  );
}